<?php if(count($this->qs) == 0) {
	echo "No queues.";
	return;
}
?>
<?php 
foreach($this->qs as $queue) {
?>
<form method="POST" action="<?= $this->url(array("action" => "send", "controller" => "queue")) ?>" style="display: inline">
Queue <?= $queue ?>: 
<input type="hidden" name="name" value="<?= $queue ?>">
<input type="submit" value="Send" style="display: inline">
</form> 
<form method="POST" action="<?= $this->url(array("action" => "receive", "controller" => "queue")) ?>" style="display: inline">
<input type="hidden" name="name" value="<?= $queue ?>">
<input type="submit" value="Receive" style="display: inline">
</form> 
<br/>
<?php } ?>