<form method="POST" enctype="multipart/form-data">
Collection name: <select name="name">
<?php foreach($this->collections as $name) {
	if($name == $this->name) {
		$checked = " selected";
	} else {
		$checked = "";
	}
	echo "<option$checked>$name</option>";
}?>
</select>
<br/>
ID: <input type="text" name="id"/><br/>
Fields:<br/> 
<?php for($i=0;$i<$this->fieldcount; $i++) { ?>
<input type="text" name="field[<?= $i ?>][name]"/>: <input type="text" name="field[<?= $i ?>][value]"/><br/>
<?php } ?>
<input type="submit" value="Add!"/>
</form>